# Generated by Django 3.1.7 on 2021-06-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSocial', '0003_auto_20210623_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
