# Generated by Django 3.1.7 on 2021-06-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSocial', '0006_auto_20210623_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
